export default {
  products: [
    {
      _id: "1",  
      name: "Slim shirt",
      categories: "Shirts",
      image: "/images/Capture.PNG",
      price: 60,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
    },

    {
      _id: "2",
      name: "fit shirt",
      categories: "Shirts",
      image: "/images/Capture1.PNG",
      price: 100,
      brand: "Nike",
      rating: 3.5,
      numReviews: 10,
    },

    {
        _id: "3",
      name: "Slim shirt",
      categories: "Pants",
      image: "/images/Capture2.PNG",
      price: 80,
      brand: "Nike",
      rating: 5.0,
      numReviews: 10,
    },
    {
      _id: "4",  
      name: "Slim shirt",
      categories: "Shirts",
      image: "/images/Capture3.PNG",
      price: 60,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
    },

    {
      _id: "5",
      name: "fit shirt",
      categories: "Shirts",
      image: "/images/Capture4.PNG",
      price: 100,
      brand: "Nike",
      rating: 3.5,
      numReviews: 10,
    },

    {
        _id: "6",
      name: "Slim shirt",
      categories: "Pants",
      image: "/images/Capture5.PNG",
      price: 80,
      brand: "Nike",
      rating: 5.0,
      numReviews: 10,
    },
    {
      _id: "7",  
      name: "Slim shirt",
      categories: "Shirts",
      image: "/images/Capture6.PNG",
      price: 60,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
    },

    {
      _id: "8",
      name: "fit shirt",
      categories: "Shirts",
      image: "/images/Capture7.PNG",
      price: 100,
      brand: "Nike",
      rating: 3.5,
      numReviews: 10,
    },

    {
        _id: "9",
      name: "Slim shirt",
      categories: "Pants",
      image: "/images/Capture8.PNG",
      price: 80,
      brand: "Nike",
      rating: 5.0,
      numReviews: 10,
    },
    {
      _id: "10",  
      name: "Slim shirt",
      categories: "Shirts",
      image: "/images/Capture9.PNG",
      price: 60,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
    },

    {
      _id: "11",
      name: "fit shirt",
      categories: "Shirts",
      image: "/images/Capture10.PNG",
      price: 100,
      brand: "Nike",
      rating: 3.5,
      numReviews: 10,
    },

    {
        _id: "12",
      name: "Slim shirt",
      categories: "Pants",
      image: "/images/Capture11.PNG",
      price: 80,
      brand: "Nike",
      rating: 5.0,
      numReviews: 10,
    },
    {
      _id: "13",  
      name: "Slim shirt",
      categories: "Shirts",
      image: "/images/Capture12.PNG",
      price: 60,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
    },

    {
      _id: "14",
      name: "fit shirt",
      categories: "Shirts",
      image: "/images/Capture13.PNG",
      price: 100,
      brand: "Nike",
      rating: 3.5,
      numReviews: 10,
    },

    {
        _id: "15",
      name: "Slim shirt",
      categories: "Pants",
      image: "/images/Capture14.PNG",
      price: 80,
      brand: "Nike",
      rating: 5.0,
      numReviews: 10,
    },
  ],
};
